eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
server:
  port: 9003
spring:
  application:
    name: userweb03
  thymeleaf:
    cache: false
  cloud:
    loadbalancer:
      retry:
        enabled: true
USERPROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
      # Ribbon的连接超时时间
    ConnectTimeout: 250
      # Ribbon的数据读取超时时间
    ReadTimeout: 1000
      # 是否对所有操作都进行重试
    OkToRetryOnAllOperations: true
      # 切换实例的重试次数
    MaxAutoRetriesNextServer: 1
      # 对当前实例的重试次数
    MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
